### ISSUE TITLE
Make 'Save New Group' GUI button not require a chat message

### ISSUE THREAD

**Issue by JasonHorkles** [Esophose/PlayerParticles#64] opened 2020-12-03 05:31 UTC
My server's chat is handled by Bungee, so sending a message doesn't register when using the 'Save New Group' GUI button. It would be cool if this would instead open up an Anvil GUI or something to set the name there so there aren't any conflicts

**Comment by Esophose** [comment] 2020-12-03 05:34
Duplicate of #49 
I'm trying to avoid having to rely on any sort of anvil gui since it requires version dependent code. The best way around it is to just use `/pp group save <name>`, I suppose there could be a setting to disable the functionality of the GUI button. I'm open to suggestions

**Comment by JasonHorkles** [comment] 2020-12-03 05:38
You could have it send a chat message or something when clicked saying "Click **here** to save a new group" and clicking it would autofill the `/pp group save <groupName>` command, or just a way to disable clicking the item in general so it just shows text explaining what to do

Yeah the bungee plugin cancels the chat from being sent to the server itself - I could set it to also pass the message to the server but then it'll have double messages

**Comment by JasonHorkles** [comment] 2020-12-03 05:39
atm I have it do this
![image](https://user-images.githubusercontent.com/51760372/100968776-37a01c00-34ef-11eb-8b56-a15c8e74ea01.png)
and
![image](https://user-images.githubusercontent.com/51760372/100968787-3d95fd00-34ef-11eb-804f-d5fe62e60497.png)
when clicked

**Comment by Esophose** [comment] 2020-12-03 05:41
I really like the solution with the clickable text to copy a command to the chat input box. I'll add a setting for that in a day or two, if I forget please just respond here or ping me on discord and I'll get on it.

**Comment by JasonHorkles** [comment] 2020-12-03 05:44
Sounds good, thanks so much!!

**Comment by Esophose** [comment] 2020-12-06 01:10
This has been added and will be in the v7.17 release.

**Closed by Esophose** 2020-12-06 01:10 UTC
Labels: duplicate, enhancement
