### ISSUE TITLE
Particle style Arrows causes memory leak

### ISSUE THREAD

**Issue by Xayanix** [Esophose/PlayerParticles#73] opened 2021-03-03 01:14 UTC
![image](https://user-images.githubusercontent.com/12672902/109737315-1cb07700-7bc6-11eb-813d-b2de4fed6d73.png)

**Comment by Esophose** [comment] 2021-03-03 01:31
I don't see how it could be possible for it to cause a memory leak, there are 3 different checks to make sure that the arrows are getting removed from the array https://github.com/Esophose/PlayerParticles/blob/master/src/main/java/dev/esophose/playerparticles/styles/ParticleStyleArrows.java#L37

**Comment by Xayanix** [comment] 2021-03-03 16:06
Well, im using latest version and it consumes ~1.5G of memory.

**Comment by HexedHero** [comment] 2021-04-03 16:36
Unable to reproduce this in any way, spawning 5 arrows per tick for 10+ mins in loaded and unloaded chunks with instantly high config settings to make PP track all my arrows.

**Comment by Esophose** [comment] 2021-04-20 03:04
Closing as unable to reproduce

**Closed by Esophose** 2021-04-20 03:04 UTC
